-- Create author table
CREATE TABLE Author(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    first_name VARCHAR(100),
    last_name VARCHAR(100)
);

-- Create book table
CREATE TABLE Game(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id       integer,
    author_id      integer,
    publish_date   date,
    archived       boolean,
    multiplayer    VARCHAR(3),
    last_played_at date,
    FOREIGN KEY(genre_id) REFERENCES Genre(id)
    FOREIGN KEY(author_id) REFERENCES Author(id)
    FOREIGN KEY(label_id) REFERENCES Label(id)
);
